name: ratix
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Paketleri ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2

  # --- API & Ağ ---
  http: ^1.2.0
  cached_network_image: ^3.4.1

  # --- UI ve Araçlar ---
  provider: ^6.1.2
  google_fonts: ^6.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Geliştirici Araçları
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# İkon Ayarları (En altta ve en solda olmalı)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21